# Generated by Django 5.1.7 on 2025-04-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voter",
                "verbose_name_plural": "Voters",
                "db_table": "voters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoterField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("datetime", "Date/Time"),
                            ("boolean", "Boolean"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Voter Field",
                "verbose_name_plural": "Voter Fields",
                "db_table": "voter_fields",
                "ordering": ["name"],
            },
        ),
    ]
