# Generated by Django 5.1.7 on 2025-04-10 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "temple",
                    models.CharField(
                        choices=[
                            ("Sri Mahakaaleshwar Mandir", "Sri Mahakaaleshwar Mandir"),
                            (
                                "Tirumala Tirupati Devasthanam",
                                "Tirumala Tirupati Devasthanam",
                            ),
                            (
                                "Dwaraka Tirumala Devasthanam",
                                "Dwaraka Tirumala Devasthanam",
                            ),
                            (
                                "Sree Padmanabha Swamy Devasthanam",
                                "Sree Padmanabha Swamy Devasthanam",
                            ),
                            ("Sri Bhramaramba", "Sri Bhramaramba"),
                            (
                                "Mallikarjuna Swamy Varla Devasthanam",
                                "Mallikarjuna Swamy Varla Devasthanam",
                            ),
                            (
                                "Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple",
                                "Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple",
                            ),
                            (
                                "Shri Shirdi Sayee Samsthan",
                                "Shri Shirdi Sayee Samsthan",
                            ),
                            (
                                "Sabarimala Sree Ayyappa Devasthanam",
                                "Sabarimala Sree Ayyappa Devasthanam",
                            ),
                            ("Shree Jagannath Temple", "Shree Jagannath Temple"),
                            (
                                "Shri Kashi Vishwanath Temple",
                                "Shri Kashi Vishwanath Temple",
                            ),
                            (
                                "Swayambhu Sri Varasiddhi Vinayaka Swamy",
                                "Swayambhu Sri Varasiddhi Vinayaka Swamy",
                            ),
                            (
                                "Sri Kamakshi Ambal Devasthanam",
                                "Sri Kamakshi Ambal Devasthanam",
                            ),
                            ("Ram Lala Ayodha", "Ram Lala Ayodha"),
                            (
                                "Arulmigu Arunachaleswarar Temple",
                                "Arulmigu Arunachaleswarar Temple",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "no_of_persons",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("id_proof", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
