# Generated by Django 5.1.7 on 2025-04-11 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "temple",
                    models.CharField(
                        choices=[
                            ("Mahakaaleshwar", "Sri Mahakaaleshwar Mandir"),
                            ("Tirupati", "Tirumala Tirupati Devasthanam"),
                            ("Dwaraka", "Dwaraka Tirumala Devasthanam"),
                            ("Padmanabha", "Sree Padmanabha Swamy Devasthanam"),
                            (
                                "Bhramaramba",
                                "Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam",
                            ),
                            (
                                "Kalahasti",
                                "Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple",
                            ),
                            ("Shirdi", "Shri Shirdi Sayee Samsthan"),
                            ("Sabarimala", "Sabarimala Sree Ayyappa Devasthanam"),
                            ("Jagannath", "Shree Jagannath Temple"),
                            ("Kashi", "Shri Kashi Vishwanath Temple"),
                            ("Vinayaka", "Swayambhu Sri Varasiddhi Vinayaka Swamy"),
                            ("Kamakshi", "Sri Kamakshi Ambal Devasthanam"),
                            ("RamLala", "Ram Lala Ayodha"),
                            ("Arunachaleswarar", "Arulmigu Arunachaleswarar Temple"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "persons",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("visit_date", models.DateField()),
                ("id_proof", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Temple Passes",
                "unique_together": {("temple", "visit_date")},
            },
        ),
        migrations.DeleteModel(
            name="PassRequest",
        ),
    ]
