# Generated by Django 5.1.7 on 2025-04-11 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passes", "0002_templepass_delete_passrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templepass",
            options={
                "verbose_name": "Temple Pass",
                "verbose_name_plural": "Temple Passes",
            },
        ),
        migrations.AlterUniqueTogether(
            name="templepass",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="id_proof",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="persons",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="temple",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mahakaaleshwar", "Sri Mahakaaleshwar Mandir"),
                    ("Tirupati", "Tirumala Tirupati Devasthanam"),
                    ("Dwaraka", "Dwaraka Tirumala Devasthanam"),
                    ("Padmanabha", "Sree Padmanabha Swamy Devasthanam"),
                    (
                        "Bhramaramba",
                        "Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam",
                    ),
                    (
                        "Kalahasti",
                        "Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple",
                    ),
                    ("Shirdi", "Shri Shirdi Sayee Samsthan"),
                    ("Sabarimala", "Sabarimala Sree Ayyappa Devasthanam"),
                    ("Jagannath", "Shree Jagannath Temple"),
                    ("Kashi", "Shri Kashi Vishwanath Temple"),
                    ("Vinayaka", "Swayambhu Sri Varasiddhi Vinayaka Swamy"),
                    ("Kamakshi", "Sri Kamakshi Ambal Devasthanam"),
                    ("RamLala", "Ram Lala Ayodha"),
                    ("Arunachaleswarar", "Arulmigu Arunachaleswarar Temple"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templepass",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PassRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "temple",
                    models.CharField(
                        choices=[
                            ("Mahakaaleshwar", "Sri Mahakaaleshwar Mandir"),
                            ("Tirupati", "Tirumala Tirupati Devasthanam"),
                            ("Dwaraka", "Dwaraka Tirumala Devasthanam"),
                            ("Padmanabha", "Sree Padmanabha Swamy Devasthanam"),
                            (
                                "Bhramaramba",
                                "Sri Bhramaramba Mallikarjuna Swamy Varla Devasthanam",
                            ),
                            (
                                "Kalahasti",
                                "Sri Gnanaprasunambika Sametha Srikalahasteeswara Temple",
                            ),
                            ("Shirdi", "Shri Shirdi Sayee Samsthan"),
                            ("Sabarimala", "Sabarimala Sree Ayyappa Devasthanam"),
                            ("Jagannath", "Shree Jagannath Temple"),
                            ("Kashi", "Shri Kashi Vishwanath Temple"),
                            ("Vinayaka", "Swayambhu Sri Varasiddhi Vinayaka Swamy"),
                            ("Kamakshi", "Sri Kamakshi Ambal Devasthanam"),
                            ("RamLala", "Ram Lala Ayodha"),
                            ("Arunachaleswarar", "Arulmigu Arunachaleswarar Temple"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "persons",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("visit_date", models.DateField()),
                ("id_proof", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "unique_together": {("temple", "visit_date")},
            },
        ),
        migrations.AddField(
            model_name="templepass",
            name="pass_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="passes.passrequest",
            ),
        ),
        migrations.RemoveField(
            model_name="templepass",
            name="created_at",
        ),
    ]
